# Application config
spring:
  application:
    name: cart-service
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
  datasource:    url: jdbc:h2:mem:cartdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver

# HTTP Server (Tomcat) Port
server: 
  port: 8084

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:1111/eureka/
        